config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :simple_file_uploads
  root 'accounts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/simple_file_upload.rb
class SimpleFileUpload < ApplicationRecord
    mount_uploader :s3_file, S3FileUploader

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:transaction_type, :amount, :day)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_file_uploads_controller.rb
class SimpleFileUploadsController < ApplicationController
  before_action :set_simple_file_upload, only: %i[ show edit update destroy ]

  # GET /simple_file_uploads or /simple_file_uploads.json
  def index
    @simple_file_uploads = SimpleFileUpload.all
  end

  # GET /simple_file_uploads/1 or /simple_file_uploads/1.json
  def show
  end

  # GET /simple_file_uploads/new
  def new
    @simple_file_upload = SimpleFileUpload.new
  end

  # GET /simple_file_uploads/1/edit
  def edit
  end

  # POST /simple_file_uploads or /simple_file_uploads.json
  def create
    @simple_file_upload = SimpleFileUpload.new(simple_file_upload_params)

    respond_to do |format|
      if @simple_file_upload.save
        format.html { redirect_to simple_file_upload_url(@simple_file_upload), notice: "Simple file upload was successfully created." }
        format.json { render :show, status: :created, location: @simple_file_upload }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @simple_file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simple_file_uploads/1 or /simple_file_uploads/1.json
  def update
    respond_to do |format|
      if @simple_file_upload.update(simple_file_upload_params)
        format.html { redirect_to simple_file_upload_url(@simple_file_upload), notice: "Simple file upload was successfully updated." }
        format.json { render :show, status: :ok, location: @simple_file_upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @simple_file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simple_file_uploads/1 or /simple_file_uploads/1.json
  def destroy
    @simple_file_upload.destroy

    respond_to do |format|
      format.html { redirect_to simple_file_uploads_url, notice: "Simple file upload was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simple_file_upload
      @simple_file_upload = SimpleFileUpload.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def simple_file_upload_params
      params.require(:simple_file_upload).permit(:name, :s3_file)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_file_uploads_helper.rb
module SimpleFileUploadsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :transaction_type %>
    <%= form.text_field :transaction_type %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Transaction type</th>
      <th>Amount</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.transaction_type %></td>
        <td><%= account.amount %></td>
        <td><%= account.day %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction type:</strong>
  <%= @account.transaction_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @account.amount %>
</p>

<p>
  <strong>Day:</strong>
  <%= @account.day %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LambdaTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_file_uploads/_form.html.erb
<%= form_with(model: simple_file_upload) do |form| %>
  <% if simple_file_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(simple_file_upload.errors.count, "error") %> prohibited this simple_file_upload from being saved:</h2>

      <ul>
        <% simple_file_upload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :s3_file %>
    <%= form.file_field :s3_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/simple_file_uploads/edit.html.erb
<h1>Editing Simple File Upload</h1>

<%= render 'form', simple_file_upload: @simple_file_upload %>

<%= link_to 'Show', @simple_file_upload %> |
<%= link_to 'Back', simple_file_uploads_path %>

app/views/simple_file_uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Simple File Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>S3 file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @simple_file_uploads.each do |simple_file_upload| %>
      <tr>
        <td><%= simple_file_upload.name %></td>
        <td><%= simple_file_upload.s3_file %></td>
        <td><%= link_to 'Show', simple_file_upload %></td>
        <td><%= link_to 'Edit', edit_simple_file_upload_path(simple_file_upload) %></td>
        <td><%= link_to 'Destroy', simple_file_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simple File Upload', new_simple_file_upload_path %>

app/views/simple_file_uploads/new.html.erb
<h1>New Simple File Upload</h1>

<%= render 'form', simple_file_upload: @simple_file_upload %>

<%= link_to 'Back', simple_file_uploads_path %>

app/views/simple_file_uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @simple_file_upload.name %>
</p>

<p>
  <strong>S3 file:</strong>
  <%= @simple_file_upload.s3_file %>
</p>

<%= link_to 'Edit', edit_simple_file_upload_path(@simple_file_upload) %> |
<%= link_to 'Back', simple_file_uploads_path %>